### ISSUE TITLE
Annoying bug

### ISSUE THREAD

**Issue by roose** [Varriount/NimLime#71]
Every time when file saving, plugin opens new empty `nimlime` file, I disabled ALL settings, but no, it is still opens

**Comment by Varriount** [comment]
I'm sorry but I can't reproduce this on a clean install. Are you using the stable version right from Package Control, or the unstable code directly from the repository?

**Comment by roose** [comment]
Windows 10
Sublime Text 3, 
NimLime 1.2.8 from Package Control 

seems as if plugin don't read user settings
(sorry for my english)

**Comment by Varriount** [comment]
Some more questions:
- Can you give me a printout of your PATH variable?
- What other plugins do you have installed?
- Does the error occur consistantly, after uninstalling and reinstalling NimLime?

**Comment by roose** [comment]
reinstall don't help

plugins:
```
AdvancedNewFile
AutoFileName
Calculate
Color Highlighter
ColorPicker
CSS Color Converter
Emmet
FileDiffs
Markdown Preview
MarkdownEditing
Nettuts+ Fetch
NimLime
Package Control
Pretty JSON
PyV8
SideBarEnhancements
```
PATH:
```
C:\Program Files\ConEmu\ConEmu\Scripts
C:\Program Files\ConEmu
C:\Program Files\ConEmu\ConEmu
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\Program Files\Sublime Text 3
C:\ProgramData\chocolatey\bin
C:\Program Files\nodejs\
C:\Program Files\Microsoft SQL Server\120\Tools\Binn\
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
C:\Program Files\Git\cmd
C:\Users\User\AppData\Local\Programs\Python\Python35\Scripts\
C:\Users\User\AppData\Local\Programs\Python\Python35\
C:\Program Files (x86)\Git\bin
C:\Program Files (x86)\Git\libexec\git-core
C:\Program Files (x86)\MSBuild\12.0\Bin
C:\Users\User\cmdutils
C:\Users\User\AppData\Roaming\npm
C:\Users\User\vcbuild\vcbuildFixForNode
C:\Program Files\mingw-w64\x86_64-4.9.1-win32-sjlj-rt_v3-rev3\mingw64\bin
C:\Nim\dist\babel
C:\Nim\bin
C:\Program Files (x86)\GnuWin32\bin
```

**Comment by lntmny** [comment]
something useful
```py
Traceback (most recent call last):
  File "D:\workapp\sublime text 3\sublime_plugin.py", line 568, in run_
    return self.run(edit, **args)
  File "D:\workapp\SUBLIM~1\Data\INSTAL~1\NIMLIM~1.SUB\nimlime_core\commands\output_helper.py", line 15, in run
ValueError: need more than 1 value to unpack
```

**Comment by Varriount** [comment]
@roose Still haven't found the problem, as I can't replicate it on my machine. Do you have the same problem using the development version from the repository?

**Comment by lntmny** [comment]
我恰恰恰 Sublime Text 3 Build 3114

file nimlime_core/commands/output_helper.py 
``` py
    def run(self, *pargs, **kwargs):
	        edit_obj, action, args = pargs
	        if action == 'insert':
```
file NimLime/nimlime_core/utils/mixins.py
``` py
        output_view.run_command(
	            'nimlime_output',
	            dict(action='insert', args=(output_view.size(), content))
```

**Comment by Varriount** [comment]
This is fixed by a recent commit on the master branch, if you use that. Otherwise, I should be pushing out a new stable version to Package Control this weekend.

**Comment by roose** [comment]
NimLime 1.2.11 all ok, thanks )

**Comment by a-y-u-s-h** [comment]
I'm getting this error with v1.12.16, tried reinstalling but the issue persists.

Before save: 

![2019-03-08_21-46-33_screenshot](https://user-images.githubusercontent.com/19586719/54040642-e49b1700-41eb-11e9-9bed-e9f95229c6d6.png)

After Save (One more floating window pops up showing me errors, screen capture can't capture it because it vanishes on any key press)

![2019-03-08_21-46-45_screenshot](https://user-images.githubusercontent.com/19586719/54040700-04cad600-41ec-11e9-8fd5-8e03bdd12c58.png)

To get highlight back to normal, have to open the file once again.

Nimlime tab shows this:

![2019-03-08_21-47-35_screenshot](https://user-images.githubusercontent.com/19586719/54040718-0d231100-41ec-11e9-82d1-3541fb3c60d1.png)
